version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: aidata
      MONGO_INITDB_ROOT_USERNAME: hasib
      MONGO_INITDB_ROOT_PASSWORD: hasib_100
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

networks:
  my-network:

volumes:
  mongo-data: